### ISSUE TITLE
Broken by unicore/Name.pl change in 5.32

### ISSUE THREAD

**Issue by ilmari** [rjbs/App-Uni#2]
The return value of `require 'unicore/Name.pl'` has changed from lines of tab-separated codepoint/name pairs to paragraphs of newline-separated pairs:

```
$ perl5.30.0 -e 'print require "unicore/Name.pl"' |head -n6
00000	NULL
00000	NUL
00001	START OF HEADING
00001	SOH
00002	START OF TEXT
00002	STX
$ perl5.32.0 -e 'print require "unicore/Name.pl"' |head -n6
00000
NULL

00000
NUL

```

**Comment by jjatria** [comment]
This was fixed in 7a064a09e1b and released to CPAN as 9.004
